from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
    url(r'^(?P<slug>[\w-]+)/$', 'schools.views.home', name='school_home'),
    url(r'^(?P<slug>[\w-]+)/edit/$', 'schools.views.edit', name='schools_edit'),
    url(r'^(?P<slug>[\w-]+)/edit/image/$', 'schools.views.edit_image',
      name='schools_edit_image'),
    url(r'^(?P<slug>[\w-]+)/edit/ajax_image/$', 'schools.views.edit_image_async',
      name='schools_edit_image_async'),
    url(r'^(?P<slug>[\w-]+)/edit/organizers/$',
      'schools.views.edit_organizers',
      name='schools_edit_organizers'),
    url(r'^(?P<slug>[\w-]+)/edit/organizers/matching_non_organizers/$',
      'schools.views.matching_non_organizers',
      name='matching_non_organizers'),
    url(r'^(?P<slug>[\w-]+)/edit/featured/$',
      'schools.views.edit_featured',
      name='schools_edit_featured'),
    url(r'^(?P<slug>[\w-]+)/edit/featured/(?P<project_slug>[\w-]+)/delete/$',
      'schools.views.edit_featured_delete',
      name='schools_edit_featured_delete'),
    url(r'^(?P<slug>[\w-]+)/edit/featured/matching_non_featured/$',
      'schools.views.matching_non_featured',
      name='matching_non_featured'),
    url(r'^(?P<slug>[\w-]+)/edit/declined/$',
      'schools.views.edit_declined',
      name='schools_edit_declined'),
    url(r'^(?P<slug>[\w-]+)/edit/declined/(?P<project_slug>[\w-]+)/delete/$',
      'schools.views.edit_declined_delete',
      name='schools_edit_declined_delete'),
    url(r'^(?P<slug>[\w-]+)/edit/declined/matching_non_declined/$',
      'schools.views.matching_non_declined',
      name='matching_non_declined'),
)
